using System.Collections.Generic;
using UnityEngine;

public class LevelManager : MonoBehaviour
{
    public static LevelManager Instance { get; private set; }

    [Header("Level Playlist")]
    public List<LevelData> levels = new List<LevelData>();
    private int currentLevelIndex = 0;

    void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);
    }

    void Start()
    {
        if (SaveManager.Instance != null)
        {
            currentLevelIndex = SaveManager.Instance.GetCurrentLevelIndex();
        }

        // Oyuncu girer girmez baslamasin, Ana Menu ekranini gosterilsin
        if (UIManager.Instance != null)
        {
            UIManager.Instance.ToggleMainMenuPanel(true);
        }
        else
        {
            StartCurrentLevel();
        }
    }

    public void StartGameFromMenu()
    {
        StartCurrentLevel();
    }

    public void StartCurrentLevel()
    {
        if (levels.Count > 0 && currentLevelIndex < levels.Count)
        {
            GridManager.Instance.LoadLevel(levels[currentLevelIndex]);
        }
        else
        {
            // El yapimi bolumler bitti -> Yapay Zeka Seviyesi Uret
            GenerateAndLoadAILevel();
        }
    }

    public void OnLevelCompleted()
    {
        currentLevelIndex++;
        if (SaveManager.Instance != null)
        {
            SaveManager.Instance.SaveCurrentLevelIndex(currentLevelIndex);
        }
        StartCurrentLevel(); // Siradaki bolume veya AI bolumune gec
    }

    private void GenerateAndLoadAILevel()
    {
        int levelNum = currentLevelIndex + 1;
        LevelData generatedLevel = LevelGenerator.Instance.GenerateNextLevel(levelNum);
        Debug.Log($"AI LEVEL CREATED: Level {generatedLevel.levelNumber} | Generated by: {generatedLevel.discoveredBy}");
        GridManager.Instance.LoadLevel(generatedLevel);
    }
}
