using System.Collections.Generic;
using UnityEngine;

public class LevelManager : MonoBehaviour
{
    public static LevelManager Instance { get; private set; }

    [Header("Level Playlist")]
    public List<LevelData> levels = new List<LevelData>();
    private int currentLevelIndex = 0;

    void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);
    }

    void Start()
    {
        StartCurrentLevel();
    }

    public void StartCurrentLevel()
    {
        if (levels.Count > 0 && currentLevelIndex < levels.Count)
        {
            GridManager.Instance.LoadLevel(levels[currentLevelIndex]);
        }
        else
        {
            // El yapýmý bölümler bitti -> Yapay Zeka Seviyesi Üret
            GenerateAndLoadAILevel();
        }
    }

    public void OnLevelCompleted()
    {
        currentLevelIndex++;
        StartCurrentLevel(); // Sýradaki bölüme veya AI bölümüne geç
    }

    private void GenerateAndLoadAILevel()
    {
        LevelData generatedLevel = LevelGenerator.Instance.GenerateNextLevel();
        Debug.Log($"AI LEVEL CREATED: Level {generatedLevel.levelNumber} | Generated by: {generatedLevel.discoveredBy}");
        GridManager.Instance.LoadLevel(generatedLevel);
    }
}